spring:
    datasource:
        driverClassName: org.h2.Driver
        password: pw
        url: jdbc:h2:mem:test
        username: sa
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
